### PR TITLE
Resources File

### PR DESCRIPTION
**Pull request by rusrushal13**

### CODE REVIEW

**Comment by shubhamjain0594** [comment]
Can you add a small description of the book, so that for someone new, he/she will know what to expect from the book and what it is for.

**Comment by rusrushal13** [comment]
Okay.
Done

**Comment by shubhamjain0594** [comment]
You can remove the last line, since we are creating a public repository, let us keep it a repo which we can showcase. Let me know your views on this.

**Comment by shubhamjain0594** [comment]
Thanks.

**Pull request merged**
